var song1 = {
    "songLen": 37,
    "songData": [
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 192,
            "osc1_waveform": 3,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 7,
            "osc2_xenv": 0,
            "osc2_vol": 201,
            "osc2_waveform": 3,
            "noise_fader": 0,
            "env_attack": 789,
            "env_sustain": 1234,
            "env_release": 13636,
            "env_master": 191,
            "fx_filter": 2,
            "fx_freq": 5839,
            "fx_resonance": 254,
            "fx_delay_time": 6,
            "fx_delay_amt": 121,
            "fx_pan_freq": 6,
            "fx_pan_amt": 147,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 6,
            "lfo_amt": 195,
            "lfo_waveform": 0,
            "p": [
                1,
                2,
                0,
                0,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        157,
                        0,
                        0,
                        0,
                        156,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        157,
                        0,
                        0,
                        0,
                        159,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 18,
            "osc2_xenv": 1,
            "osc2_vol": 191,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 3997,
            "env_sustain": 56363,
            "env_release": 100000,
            "env_master": 255,
            "fx_filter": 2,
            "fx_freq": 392,
            "fx_resonance": 255,
            "fx_delay_time": 8,
            "fx_delay_amt": 69,
            "fx_pan_freq": 5,
            "fx_pan_amt": 67,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 4,
            "lfo_amt": 57,
            "lfo_waveform": 3,
            "p": [
                1,
                2,
                1,
                2,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        130,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        123,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 60,
            "env_attack": 50,
            "env_sustain": 419,
            "env_release": 4607,
            "env_master": 130,
            "fx_filter": 1,
            "fx_freq": 10332,
            "fx_resonance": 120,
            "fx_delay_time": 4,
            "fx_delay_amt": 16,
            "fx_pan_freq": 5,
            "fx_pan_amt": 108,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 5,
            "lfo_amt": 187,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        147,
                        147,
                        0,
                        0,
                        147,
                        0,
                        0,
                        147,
                        0,
                        147,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        147,
                        147,
                        0,
                        0,
                        147,
                        0,
                        0,
                        147,
                        0,
                        147
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 255,
            "osc1_waveform": 0,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 255,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 50,
            "env_sustain": 150,
            "env_release": 4800,
            "env_master": 200,
            "fx_filter": 2,
            "fx_freq": 600,
            "fx_resonance": 254,
            "fx_delay_time": 0,
            "fx_delay_amt": 0,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                1,
                1,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 2,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 9,
            "osc2_xenv": 0,
            "osc2_vol": 154,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 2418,
            "env_sustain": 1075,
            "env_release": 10614,
            "env_master": 240,
            "fx_filter": 3,
            "fx_freq": 2962,
            "fx_resonance": 255,
            "fx_delay_time": 6,
            "fx_delay_amt": 117,
            "fx_pan_freq": 3,
            "fx_pan_amt": 73,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 5,
            "lfo_amt": 124,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                2,
                1,
                2
            ],
            "c": [
                {
                    "n": [
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        157,
                        0,
                        0,
                        0,
                        156,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        154,
                        0,
                        154,
                        0,
                        152,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        154,
                        0,
                        147,
                        0,
                        152,
                        0,
                        157,
                        0,
                        0,
                        0,
                        159,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 192,
            "osc1_waveform": 1,
            "osc2_oct": 6,
            "osc2_det": 0,
            "osc2_detune": 9,
            "osc2_xenv": 0,
            "osc2_vol": 192,
            "osc2_waveform": 1,
            "noise_fader": 0,
            "env_attack": 137,
            "env_sustain": 2000,
            "env_release": 4611,
            "env_master": 192,
            "fx_filter": 1,
            "fx_freq": 982,
            "fx_resonance": 89,
            "fx_delay_time": 6,
            "fx_delay_amt": 25,
            "fx_pan_freq": 6,
            "fx_pan_amt": 77,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 3,
            "lfo_amt": 69,
            "lfo_waveform": 0,
            "p": [
                1,
                2,
                1,
                3,
                1,
                3
            ],
            "c": [
                {
                    "n": [
                        130,
                        0,
                        130,
                        0,
                        142,
                        0,
                        130,
                        130,
                        0,
                        142,
                        130,
                        0,
                        142,
                        0,
                        130,
                        0,
                        130,
                        0,
                        130,
                        0,
                        142,
                        0,
                        130,
                        130,
                        0,
                        142,
                        130,
                        0,
                        142,
                        0,
                        130,
                        0
                    ]
                },
                {
                    "n": [
                        123,
                        0,
                        123,
                        0,
                        135,
                        0,
                        123,
                        123,
                        0,
                        135,
                        123,
                        0,
                        135,
                        0,
                        123,
                        0,
                        123,
                        0,
                        123,
                        0,
                        135,
                        0,
                        123,
                        123,
                        0,
                        135,
                        123,
                        0,
                        135,
                        0,
                        123,
                        0
                    ]
                },
                {
                    "n": [
                        135,
                        0,
                        135,
                        0,
                        147,
                        0,
                        135,
                        135,
                        0,
                        147,
                        135,
                        0,
                        147,
                        0,
                        135,
                        0,
                        135,
                        0,
                        135,
                        0,
                        147,
                        0,
                        135,
                        135,
                        0,
                        147,
                        135,
                        0,
                        147,
                        0,
                        135,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 3,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 0,
            "noise_fader": 127,
            "env_attack": 22,
            "env_sustain": 88,
            "env_release": 3997,
            "env_master": 255,
            "fx_filter": 3,
            "fx_freq": 4067,
            "fx_resonance": 234,
            "fx_delay_time": 4,
            "fx_delay_amt": 33,
            "fx_pan_freq": 2,
            "fx_pan_amt": 84,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 3,
            "lfo_amt": 28,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                1,
                2,
                1,
                2,
                1,
                3
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        142,
                        0,
                        154,
                        0,
                        0,
                        0,
                        142,
                        0,
                        0,
                        0,
                        154,
                        0,
                        0,
                        0,
                        0,
                        0,
                        142,
                        0,
                        154,
                        0,
                        0,
                        0,
                        142,
                        0,
                        0,
                        0,
                        154,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        147,
                        0,
                        154,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        154,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        154,
                        0,
                        147,
                        0,
                        0,
                        0,
                        154,
                        0,
                        0,
                        0,
                        154,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        147,
                        0,
                        154,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        154,
                        0,
                        0,
                        0,
                        0,
                        0,
                        147,
                        0,
                        154,
                        0,
                        0,
                        0,
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 8,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 0,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 0,
            "osc2_waveform": 0,
            "noise_fader": 255,
            "env_attack": 140347,
            "env_sustain": 9216,
            "env_release": 133417,
            "env_master": 208,
            "fx_filter": 2,
            "fx_freq": 2500,
            "fx_resonance": 16,
            "fx_delay_time": 2,
            "fx_delay_amt": 157,
            "fx_pan_freq": 8,
            "fx_pan_amt": 207,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 2,
            "lfo_amt": 51,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        147,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "rowLen": 5513,
    "endPattern": 9
}
